import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar1 from '../comps/navbar1'
import Footer from '../comps/footer'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>NEXT JS HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar1 />
      <main className={styles.main}>

        <a href="https://www.freecodecamp.org/news/the-next-js-handbook/" >
          <img className={styles.img1} src="/nextimg.png" />
        </a>

      </main>
      <Footer />
    </div>
  )
}
